### ISSUE TITLE
Install pythorhead through requirements instead of bundling it in the bot

### ISSUE THREAD

**Issue by db0** [Demigodrick/community_bot#2]
Why did you do this? Lol :D

**Comment by Demigodrick** [comment]
Haha, too impatient to wait for the PR so just copied and pasted pythorhead out of pure laziness :)

Actually this reminded me to undo it!

**Comment by db0** [comment]
just FYI, even then you don't need to do that. You can just set up your requirements to install directly from your own branch on github

**Comment by Demigodrick** [comment]
Yep, you're absolutely right, i was just being as lazy as possible as i didnt think anyone would ever see this spaghetti code!
